### ISSUE TITLE
Support response_type other than "code"

### ISSUE THREAD

**Issue by tcrossland** [DockYard/openid_connect#14]
It would be useful to be able to specify other response types (e.g. "id_token") in the authorization_uri. Currently "code" is hard-coded.

**Comment by bcardarella** [comment]
Yes, I am in favor of this. I'm happy to review a PR if you have it otherwise it may be a bit before I can get to this as I am focused on other things at the moment.

**Comment by tcrossland** [comment]
Fixed in #17, so closing this issue.

**Comment by bcardarella** [comment]
FYI, just released v0.2.0

**Comment by tcrossland** [comment]
@bcardarella great, I've updated the dependency in our app and it's working fine. many thanks!
