### ISSUE TITLE
Proper Supervisor format for Elixir 1.7.4?

### ISSUE THREAD

**Issue by musicman3569** [DockYard/openid_connect#15]
All the documentation refers to deprecated syntax for adding the Supervisor worker to your project's 
application.ex file:
>worker(OpenIDConnect.Worker, [Application.get_env(:my_app, :openid_connect_providers)])

which will produce the compile error:
>** (CompileError) lib/eos/application.ex:19: undefined function worker/2

According to https://hexdocs.pm/elixir/Supervisor.html the new syntax is to either use a tuple:
>{OpenIDConnect.Worker, [Application.get_env(:eos, :openid_connect_providers)]}

but that produces the error: 
>** (Mix) Could not start application eos: Eos.Application.start(:normal, []) returned an error: shutdown: failed to start child: OpenIDConnect.Worker
>    ** (EXIT) an exception was raised:
>        ** (FunctionClauseError) no function clause matching in anonymous fn/1 in OpenIDConnect.Worker.init/1
>            (openid_connect) lib/openid_connect/worker.ex:22: anonymous fn([hcp: [discovery_document_uri: "https://gateway.sso.homecarepulse.com/hcp/oidc/.well-known/openid-configuration", client_id: "hcp-jason-dev", client_secret: "<REMOVED>", redirect_uri: "http://eos.hcp-jason-dev.local:4000", scope: "openid email profile"]]) in OpenIDConnect.Worker.init/1
>            (elixir) lib/map.ex:210: Map.new_transform/3
>            (openid_connect) lib/openid_connect/worker.ex:22: OpenIDConnect.Worker.init/1
>            (stdlib) gen_server.erl:374: :gen_server.init_it/2
>            (stdlib) gen_server.erl:342: :gen_server.init_it/6
>            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

or to use a map:
`%{
        id: OpenIDConnect.Worker,
        start: { OpenIDConnect.Worker, :start_link, [Application.get_env(:eos, :openid_connect_providers)] }
      }`

, but that produces the error:
>** (Mix) Could not start application eos: Eos.Application.start(:normal, []) returned an error: shutdown: failed to start child: OpenIDConnect.Worker
>    ** (EXIT) an exception was raised:
>        ** (MatchError) no match of right hand side value: {:error, :update_documents, %HTTPoison.Error{id: nil, reason: :econnrefused}}
>            (openid_connect) lib/openid_connect/worker.ex:55: OpenIDConnect.Worker.update_documents/2
>            (openid_connect) lib/openid_connect/worker.ex:23: anonymous fn/1 in OpenIDConnect.Worker.init/1
>            (elixir) lib/map.ex:210: Map.new_transform/3
>            (openid_connect) lib/openid_connect/worker.ex:22: OpenIDConnect.Worker.init/1
>            (stdlib) gen_server.erl:374: :gen_server.init_it/2
>            (stdlib) gen_server.erl:342: :gen_server.init_it/6
>            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

I've also tried various permutations with an additional set of square brackets on worker init argument and such just in case, but no luck.  I can also tell by the first error that it is able to read the environment config. It has to be some silly little syntax issue on my part, but I'm new to Phoenix/Elixir and am running out of ideas.  Thoughts? (Thanks in advance)

**Comment by bcardarella** [comment]
Can you provide the entire content of your supervisor file? I suspect the `worker` function is not being imported.

**Comment by musicman3569** [comment]
I'm assuming you mean my apps application.ex:
```elixir
defmodule Eos.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Eos.Repo,
      # Start the endpoint when the application starts
      EosWeb.Endpoint,
      # Starts a worker by calling: Eos.Worker.start_link(arg)
      # {Eos.Worker, arg},

      # Start supervisor for OpenIDConnect per https://hexdocs.pm/openid_connect/readme.html
      %{
        id: OpenIDConnect.Worker,
        start: { OpenIDConnect.Worker, :start_link, [Application.get_env(:eos, :openid_connect_providers)] }
      }
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Eos.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    EosWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end
```

This is a brand new phoenix app generated from the standard mix command, so the only change is my addition of the OpenID line.

According a post of this exact issue at https://elixirforum.com/t/undefined-function-worker-2/18341/1 usage of the `worker` function is deprecated, so I wasn't trying to get it in scope, I was trying to use the correct syntax for 1.7.4 as specified in the Supervisor docs at https://hexdocs.pm/elixir/Supervisor.html (assuming I'm understanding all this correctly).

And thanks for getting back to me!  Elixir seems to have a really great community.

**Comment by musicman3569** [comment]
After using a basic tuple format in application.ex like this:
```elixir
 def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Eos.Repo,
      # Start the endpoint when the application starts
      EosWeb.Endpoint,

      # Start supervisor for OpenIDConnect per https://hexdocs.pm/openid_connect/readme.html
      {OpenIDConnect.Worker, Application.get_env(:eos, :openid_connect_providers)},
    ]
```

I've noticed that the error is now:
```
$ mix test
Compiling 16 files (.ex)
Generated eos app
** (Mix) Could not start application eos: Eos.Application.start(:normal, []) returned an error: shutdown: failed to start child: OpenIDConnect.Worker
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, :update_documents, %HTTPoison.Error{id: nil, reason: :econnrefused}}
            (openid_connect) lib/openid_connect/worker.ex:55: OpenIDConnect.Worker.update_documents/2
            (openid_connect) lib/openid_connect/worker.ex:23: anonymous fn/1 in OpenIDConnect.Worker.init/1
            (elixir) lib/map.ex:210: Map.new_transform/3
            (openid_connect) lib/openid_connect/worker.ex:22: OpenIDConnect.Worker.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```
In particular this part of the above error: `%HTTPoison.Error{id: nil, reason: :econnrefused}`

I didn't expect it to make any HTTP connections at compile time, but it looks like it is trying to connect to my OpenIDConnect server and failing.

So perhaps the new tuple syntax _is_ working just fine for the OpenIDConnect.Worker, and the problem is really just a failed HTTP connection?  I'll check my Gravitee.io (OpenID IDP) server and post back what I find.

**Comment by musicman3569** [comment]
Solved!  There were 2 parts to this:

1. The documentation at https://hexdocs.pm/openid_connect/readme.html is incorrect for the latest Phoenix 1.4 + Elixir 1.7.4 (which is what you will get for a new project by default).  The code snippet in the Worker section of the page:
```elixir
children =
  [
    worker(OpenIDConnect.Worker, [Application.get_env(:my_app, :openid_connect_providers)]),
  ]

opts = [strategy: :one_for_one, name: DockYard.Supervisor]
Supervisor.start_link(children, opts)
```
needs to be changed for Elixir 1.7.4 to be:
```elixir
children =
  [
    {OpenIDConnect.Worker, Application.get_env(:my_app, :openid_connect_providers)},
  ]

opts = [strategy: :one_for_one, name: DockYard.Supervisor]
Supervisor.start_link(children, opts)
```
That simply syntax change was the only issue with openid_connect.

2. The second issue was not related to Elixir at all.  It turned out to be an issue with my Nginx reverse proxy for my Identity Provider server not adding the proxy_set_header values, causing the `.well-known/openid-configuration` to return endpoints with `localhost`.  This caused the compile to fail.

Cheers!

**Comment by bcardarella** [comment]
@musicman3569 awesome, thanks for sticking in there on that. If you'd like the PR the documentation updates that would be much appreciated!
